### ISSUE TITLE
Warning: Calling ENV.j1 is deprecated! when brew install cachalot

### ISSUE THREAD

**Issue by twerthmueller** [amazeeio/cachalot#3]
Hi

I got the following warning when I install cachalot over brew:

```
Warning: Calling ENV.j1 is deprecated!
Use ENV.deparallelize instead.
/usr/local/Homebrew/Library/Taps/amazeeio/homebrew-cachalot/Formula/unfs3.rb:23:in `install'
Please report this to the amazeeio/cachalot tap!

```

Thanks for having a look on it,
Thomas

**Comment by dasrecht** [comment]
Hi @twerthmueller I remember we discussed that on Slack, did the ruby update solve the issue for you?

**Comment by twerthmueller** [comment]
Yes, I think it was the Ruby update. What's for sure, I don't have the problem anymore. Sorry that I didn't close this issue!
