### ISSUE TITLE
Cachalot's nfs slow as hell when using drupal 7 

### ISSUE THREAD

**Issue by stmh** [amazeeio/cachalot#9]
Hi,

we are evaluating cachalot as a replacement for our custom vagrant setup. For D8 the performance is great and in most cases better than our vagrant setup.

But for D7 it's really bad, doing a `cache clear all` takes for one installation 30 minutes, and using our setup ~2minutes. (unfs will consume 100% of one cpu while doing a cache clear)

The perplexing part is that our setup is similar to cachalot (vagrant as a docker container, mount the user directory via nfs into vagrant, haproxy as a reverse proxy feeding the traffic to the running docker containers, if you are interested have a look at https://github.com/factorial-io/multibasebox)

Is there a way to tune the unfs-performance for cachalot with some hidden settings maybe?

**Comment by dasrecht** [comment]
Hi @stmh 

this is weird usually it shoudln't be that slow. Can it maybe be that you have a node_modules folder within your theme folder?

We saw this behaviour earlier on Drupal installations. Usually it shouldn't take too long.

Drupal 7 - https://www.drupal.org/project/drupal/issues/2482549
Drupal 8 - https://www.drupal.org/project/drupal/issues/2393605

/bastian
